POST https://h3fm7drq7l.execute-api.eu-north-1.amazonaws.com/dev/api/v1/forms HTTP/1.1

{
  "body": {
    "userId": 123,
    "answers": [
      {
        "id": 321,
        "content": "Hello Dudd!"
      },
      {
        "id": 123,
        "content": "I am cool!"
      },
      {
        "id": 789,
        "content": "This is my final answer!"
      }
    ]
  }
}