version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "unsafe-perm=true" > .npmrc
      - echo "registry=https://registry.yarnpkg.com/" >> .npmrc
      - echo "@helsingborg-stad:registry=https://npm.pkg.github.com" >> .npmrc
      - echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
      - echo "always-auth=true" >> .npmrc
      - npm install -g yarn
      - yarn global add serverless@3.26.0
      - yarn install
      - cd .deploy
      - yarn install
      - cd ..
  build:
    commands:
      - CRED=`aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_NBR:role/ServerlessDeployRole --role-session-name env-access`
      - AWS_ACCESS_KEY_ID=`node -pe 'JSON.parse(process.argv[1]).Credentials.AccessKeyId' "$CRED"`
      - AWS_SECRET_ACCESS_KEY=`node -pe 'JSON.parse(process.argv[1]).Credentials.SecretAccessKey' "$CRED"`
      - AWS_SESSION_TOKEN=`node -pe 'JSON.parse(process.argv[1]).Credentials.SessionToken' "$CRED"`
      - AWS_EXPIRATION=`node -pe 'JSON.parse(process.argv[1]).Credentials.Expiration' "$CRED"`
      - node --max_old_space_size=6144 .deploy /root/last-build/last-deployed-commit-sha-$ENV
      - mkdir -p /root/last-build
      - git rev-parse HEAD > /root/last-build/last-deployed-commit-sha-$ENV
cache:
  paths:
    - node_modules/**/*
    - /usr/local/share/.config/yarn/**/*
    - /usr/local/share/.cache/yarn/v6/**/*
    - /root/last-build/**/*
    - /root/.npm/**/*
